INPUT_PATH = "input/"
OUTPUT_PATH = "output/"

OUTPUT_REALTIME_DETECTED_PLATES = OUTPUT_PATH + "realtime_detected.csv"

OUTPUT_RESULTS = OUTPUT_PATH + "results.csv"

OUTPUT_INTERPOLATED_RESULTS = OUTPUT_PATH + "results_interpolated.csv"

OUTPUT_GENERATED_VISION_RESULTS = OUTPUT_PATH + "out.mp4"

INPUT_SAMPLE = INPUT_PATH + "sample.mp4"
